### PR TITLE
Batching

### LINKED ISSUE #2: Batching requests
https://segment.com/docs/libraries/http/#import

api could look something like this:

```ruby
analytics.batch do |batch|
  batch.identify(...)
  batch.track(...)
  batch.track(...)
  ...
end
```

### PR DESCRIPTION
**Pull request by whatthewhat**
https://segment.com/docs/libraries/http/#import

``` ruby
analytics.batch do |batch|
  batch.context = {...}
  batch.integrations = {...}
  batch.identify(...)
  batch.track(...)
  batch.track(...)
  ...
end
```

closes #2

### CODE REVIEW

**Comment by mickey** [comment]
Is there something blocking the merge of this?
Can I help in any way?

**Comment by whatthewhat** [comment]
Hey @mickey, doing some more testing, but will likely release a version today.
Any feedback appreciated :)

**Comment by mickey** [comment]
Awesome, I'm pointing my gemfile to master. Will let you know how it goes.

**Comment by whatthewhat** [comment]
Pushed `v0.1.0.pre2` with this changes to rubygems

**Pull request merged**
