### PR TITLE
Add proxy support (`http_proxy` and `https_proxy` env vars)

### PR DESCRIPTION
**Pull request by saks**
Hey! Please have a look at this PR :)
After looking into docs one more time I figured how to make it look into ENV vars, thanks :)
I'm having issues figuring out how to write a test for my change, I'd very much appreciate any help here.

Please let me know what you think.
We've tested this change in our environment and everything seems working as expected.

Thanks!

### CODE REVIEW

**Comment by saks** [comment]
hey @whatthewhat! Is there anything I can do to improve this PR to get it merged?

**Comment by whatthewhat** [comment]
Sorry @saks, I just got back from vacation. Looks like [testing this can be a challenge](https://github.com/bblimke/webmock/issues/753) - I'll dig around for some options, but seems safe enough to merge as is if there aren't good ones.

**Comment by saks** [comment]
hey @whatthewhat! Thanks for looking into it. Please let me know if you need a hand with this.

**Comment by whatthewhat** [comment]
I think this is good to go as is for now. After reading how `Net::HTTP.start` handles it's arguments I kind of want to refactor to something else in the future :)

**Pull request merged**
